### ISSUE TITLE
Relative paths aren't replaced

### ISSUE THREAD

**Issue by thulstrup** [bevacqua/scourge#1]
I found an issue where relative paths aren't replaced with the hashed value.

So this isn't working:

``` css
@font-face {
  font-family: "My Font";
  src: url("../fonts/myfont.woff2") format("woff2");
}
```

But if I use absolute paths it works:

``` css
@font-face {
  font-family: "My Font";
  src: url("/fonts/myfont.woff2") format("woff2");
}
```
